import React from 'react';
import { AlertTriangle, Info } from 'lucide-react';

export const Disclaimer = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="disclaimer-compact">
        <AlertTriangle size={16} color="#F59E0B" className="flex-shrink-0" />
        <span>
          <strong>For educational purposes only.</strong> This prediction is generated by a machine-learning model and is not a medical diagnosis.
        </span>
        <style>{`
          .disclaimer-compact {
            background-color: #FFFBEB;
            border: 1px solid #FDE68A;
            border-radius: 10px;
            padding: 0.75rem 1rem;
            font-size: 0.85rem;
            color: #92400E;
            display: flex;
            align-items: flex-start;
            gap: 0.6rem;
            line-height: 1.5;
          }
          .flex-shrink-0 { flex-shrink: 0; }
        `}</style>
      </div>
    );
  }

  return (
    <div className="disclaimer-banner">
      <div className="disclaimer-header">
        <AlertTriangle size={20} color="#F59E0B" />
        <h4>Important Clinical & Project Disclaimer</h4>
      </div>
      <p>
        <strong>Academic ML Project:</strong> This system uses trained machine learning classification models to calculate statistical risk metrics based on physiological inputs. Output results are strictly for educational demonstration and computer science portfolio presentation.
      </p>
      <p style={{ marginTop: '0.4rem' }}>
        <strong>Not a Medical Diagnosis:</strong> This software does <strong>not</strong> provide medical advice, diagnosis, or treatment. Patients and users must always consult licensed physicians or certified cardiologists for medical evaluation and blood test interpretations.
      </p>

      <style>{`
        .disclaimer-banner {
          background-color: #FFFBEB;
          border: 1.5px solid #FCD34D;
          border-radius: 14px;
          padding: 1.25rem 1.5rem;
          margin-top: 2rem;
          font-size: 0.88rem;
          color: #78350F;
          line-height: 1.6;
        }

        .disclaimer-header {
          display: flex;
          align-items: center;
          gap: 0.6rem;
          margin-bottom: 0.5rem;
        }

        .disclaimer-header h4 {
          font-size: 0.98rem;
          font-weight: 800;
          color: #92400E;
          margin: 0;
        }
      `}</style>
    </div>
  );
};

export default Disclaimer;
