import React from 'react';
import { Heart, ShieldCheck, Cpu } from 'lucide-react';

export const Footer = () => {
  return (
    <footer className="footer">
      <div className="footer-container">
        <div className="footer-top">
          <div className="footer-brand">
            <div className="footer-logo">
              <Heart fill="#DC2626" color="#DC2626" size={20} />
              <span>CardioPredict</span>
            </div>
            <p className="footer-desc">
              AI-driven cardiovascular risk early screening & analytical intelligence web application.
            </p>
          </div>

          <div className="footer-links-group">
            <div className="footer-column">
              <h4>System Links</h4>
              <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/assessment">Risk Assessment</a></li>
                <li><a href="/results">Results Dashboard</a></li>
              </ul>
            </div>

            <div className="footer-column">
              <h4>ML Analytics</h4>
              <ul>
                <li><a href="/performance">Model Performance</a></li>
                <li><a href="/dataset">Dataset Explorer</a></li>
                <li><a href="/about">Project & Methodology</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div className="footer-disclaimer">
          <p>
            <strong>Educational Project Disclaimer:</strong> CardioPredict is strictly an academic machine-learning platform built for demonstration purposes. Predictions generated by this system are based on algorithmic statistics and do <strong>NOT</strong> constitute medical advice, clinical diagnoses, or treatment recommendations. Always consult a certified healthcare professional or cardiologist for medical evaluations.
          </p>
        </div>

        <div className="footer-bottom">
          <p>© {new Date().getFullYear()} CardioPredict System. Built with React.js & Python FastAPI.</p>
          <div className="footer-tech-badges">
            <span className="footer-badge"><Cpu size={14} /> AdaBoost ML</span>
            <span className="footer-badge"><ShieldCheck size={14} /> FastAPI REST</span>
          </div>
        </div>
      </div>

      <style>{`
        .footer {
          background-color: #FFFFFF;
          border-top: 1.5px solid #E2E8F0;
          padding: 3rem 1.5rem 1.5rem 1.5rem;
          margin-top: auto;
          color: #475569;
        }

        .footer-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .footer-top {
          display: flex;
          justify-content: space-between;
          gap: 3rem;
          margin-bottom: 2rem;
          flex-wrap: wrap;
        }

        .footer-brand {
          max-width: 380px;
        }

        .footer-logo {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 1.25rem;
          font-weight: 800;
          color: #0F2747;
          margin-bottom: 0.8rem;
        }

        .footer-desc {
          font-size: 0.9rem;
          color: #64748B;
          line-height: 1.6;
        }

        .footer-links-group {
          display: flex;
          gap: 4rem;
        }

        .footer-column h4 {
          font-size: 0.95rem;
          font-weight: 700;
          color: #0F2747;
          margin-bottom: 0.8rem;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .footer-column ul {
          list-style: none;
        }

        .footer-column li {
          margin-bottom: 0.5rem;
        }

        .footer-column a {
          font-size: 0.9rem;
          color: #64748B;
          transition: color 0.2s ease;
          text-decoration: none;
        }

        .footer-column a:hover {
          color: #2563EB;
        }

        .footer-disclaimer {
          background-color: #F8FAFC;
          border: 1px solid #E2E8F0;
          border-radius: 12px;
          padding: 1rem 1.25rem;
          font-size: 0.82rem;
          color: #64748B;
          line-height: 1.6;
          margin-bottom: 2rem;
        }

        .footer-bottom {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-top: 1px solid #E2E8F0;
          padding-top: 1.5rem;
          font-size: 0.85rem;
          color: #94A3B8;
          flex-wrap: wrap;
          gap: 1rem;
        }

        .footer-tech-badges {
          display: flex;
          gap: 0.75rem;
        }

        .footer-badge {
          display: inline-flex;
          align-items: center;
          gap: 0.35rem;
          font-size: 0.78rem;
          font-weight: 600;
          background: #EFF6FF;
          color: #2563EB;
          padding: 0.3rem 0.65rem;
          border-radius: 6px;
        }
      `}</style>
    </footer>
  );
};

export default Footer;
