import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import RiskResultCard from '../components/RiskResultCard';
import SectionHeader from '../components/SectionHeader';
import MetricCard from '../components/MetricCard';
import { ArrowLeft, Activity, ShieldCheck, Heart, User } from 'lucide-react';

export const ResultsPage = ({ lastResult }) => {
  const location = useLocation();
  const navigate = useNavigate();

  const resultData = location.state?.result || lastResult;
  const formData = location.state?.formData;

  const handleReset = () => {
    navigate('/assessment');
  };

  if (!resultData) {
    return (
      <div className="results-page animate-fade-in">
        <SectionHeader
          badgeText="Evaluation Outcome"
          title="Prediction Results Dashboard"
          subtitle="No active assessment session found. Please complete the risk assessment form."
        />

        <div className="no-result-card">
          <Heart size={48} color="#94A3B8" className="empty-icon" />
          <h3>No Prediction Data Available</h3>
          <p>Please complete the cardiovascular risk evaluation form to view machine learning predictions.</p>
          <button className="btn btn-primary btn-lg" onClick={handleReset}>
            <Activity size={18} /> Start New Health Assessment
          </button>
        </div>

        <style>{`
          .no-result-card {
            background: #FFFFFF;
            border: 1.5px solid #E2E8F0;
            border-radius: 20px;
            padding: 4rem 2rem;
            text-align: center;
            margin: 2rem 0;
            box-shadow: 0 4px 16px rgba(15, 39, 71, 0.03);
          }

          .empty-icon {
            margin-bottom: 1.25rem;
          }

          .no-result-card h3 {
            font-size: 1.4rem;
            font-weight: 800;
            color: #0F2747;
            margin-bottom: 0.5rem;
          }

          .no-result-card p {
            font-size: 1rem;
            color: #64748B;
            margin-bottom: 1.75rem;
          }
        `}</style>
      </div>
    );
  }

  return (
    <div className="results-page animate-fade-in">
      <SectionHeader
        badgeText="Clinical Risk Report"
        title="Prediction Results Dashboard"
        subtitle="Algorithmic risk evaluation generated by the trained AdaBoost machine-learning model."
      />

      {/* Patient Input Summary Bar if available */}
      {formData && (
        <div className="patient-summary-bar">
          <div className="summary-item">
            <span className="summary-label">Patient Profile</span>
            <span className="summary-value">{formData.age} yrs, {formData.gender === 1 ? 'Female' : 'Male'}</span>
          </div>
          <div className="summary-item">
            <span className="summary-label">Dimensions</span>
            <span className="summary-value">{formData.height} cm / {formData.weight} kg</span>
          </div>
          <div className="summary-item">
            <span className="summary-label">Blood Pressure</span>
            <span className="summary-value">{formData.ap_hi}/{formData.ap_lo} mmHg</span>
          </div>
          <div className="summary-item">
            <span className="summary-label">Cholesterol / Glucose</span>
            <span className="summary-value">Lvl {formData.cholesterol} / Lvl {formData.gluc}</span>
          </div>
        </div>
      )}

      {/* Main Result Card */}
      <RiskResultCard result={resultData} onReset={handleReset} />

      <style>{`
        .patient-summary-bar {
          background: #FFFFFF;
          border: 1px solid #E2E8F0;
          border-radius: 14px;
          padding: 1rem 1.5rem;
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 1rem;
          margin-bottom: 1.5rem;
          box-shadow: 0 2px 8px rgba(15, 39, 71, 0.02);
        }

        .summary-item {
          display: flex;
          flex-direction: column;
        }

        .summary-label {
          font-size: 0.75rem;
          font-weight: 700;
          color: #64748B;
          text-transform: uppercase;
        }

        .summary-value {
          font-size: 0.95rem;
          font-weight: 700;
          color: #0F2747;
          margin-top: 0.15rem;
        }

        @media (max-width: 768px) {
          .patient-summary-bar {
            grid-template-columns: repeat(2, 1fr);
          }
        }
      `}</style>
    </div>
  );
};

export default ResultsPage;
